/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CustodianInterface extends ethers.utils.Interface {
  functions: {
    "MIN_COLLATERAL_RATIO()": FunctionFragment;
    "ONE_HUNDRED_PERCENT()": FunctionFragment;
    "checkBorrowerEligibility(uint256,address)": FunctionFragment;
    "createVault(address,uint256)": FunctionFragment;
    "getVaultByOwner(address)": FunctionFragment;
    "initializeContract()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "owner()": FunctionFragment;
    "registry()": FunctionFragment;
    "requireSufficientCollateral(uint256,uint256,uint256)": FunctionFragment;
    "treasury()": FunctionFragment;
    "vaults(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MIN_COLLATERAL_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONE_HUNDRED_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkBorrowerEligibility",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultByOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requireSufficientCollateral",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "vaults", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "MIN_COLLATERAL_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONE_HUNDRED_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkBorrowerEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requireSufficientCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "VaultCreated(address,uint256)": EventFragment;
    "VaultDeleted(address,uint256)": EventFragment;
    "VaultUpdated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultUpdated"): EventFragment;
}

export class Custodian extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CustodianInterface;

  functions: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        index: BigNumber;
        collateral: BigNumber;
        equity: BigNumber;
        debt: BigNumber;
        status: number;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: number;
      };
    }>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        index: BigNumber;
        collateral: BigNumber;
        equity: BigNumber;
        debt: BigNumber;
        status: number;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: number;
      };
    }>;

    initializeContract(overrides?: Overrides): Promise<ContractTransaction>;

    "initializeContract()"(overrides?: Overrides): Promise<ContractTransaction>;

    isOwner(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isOwner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    registry(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "registry()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    treasury(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "treasury()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    vaults(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    "vaults(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;
  };

  MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

  "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

  ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

  "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

  checkBorrowerEligibility(
    debt: BigNumberish,
    borrower: string,
    overrides?: CallOverrides
  ): Promise<void>;

  "checkBorrowerEligibility(uint256,address)"(
    debt: BigNumberish,
    borrower: string,
    overrides?: CallOverrides
  ): Promise<void>;

  createVault(
    owner: string,
    initialCollateral: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createVault(address,uint256)"(
    owner: string,
    initialCollateral: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getVaultByOwner(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  "getVaultByOwner(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  initializeContract(overrides?: Overrides): Promise<ContractTransaction>;

  "initializeContract()"(overrides?: Overrides): Promise<ContractTransaction>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  "registry()"(overrides?: CallOverrides): Promise<string>;

  requireSufficientCollateral(
    debt: BigNumberish,
    equity: BigNumberish,
    collateral: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "requireSufficientCollateral(uint256,uint256,uint256)"(
    debt: BigNumberish,
    equity: BigNumberish,
    collateral: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  treasury(overrides?: CallOverrides): Promise<string>;

  "treasury()"(overrides?: CallOverrides): Promise<string>;

  vaults(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  "vaults(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  callStatic: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    initializeContract(overrides?: CallOverrides): Promise<void>;

    "initializeContract()"(overrides?: CallOverrides): Promise<void>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    "registry()"(overrides?: CallOverrides): Promise<string>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    "treasury()"(overrides?: CallOverrides): Promise<string>;

    vaults(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    "vaults(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    VaultCreated(owner: string | null, vaultId: null): EventFilter;

    VaultDeleted(owner: string | null, vaultId: null): EventFilter;

    VaultUpdated(owner: string | null, vaultId: null): EventFilter;
  };

  estimateGas: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeContract(overrides?: Overrides): Promise<BigNumber>;

    "initializeContract()"(overrides?: Overrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    "registry()"(overrides?: CallOverrides): Promise<BigNumber>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    "treasury()"(overrides?: CallOverrides): Promise<BigNumber>;

    vaults(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "vaults(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeContract(overrides?: Overrides): Promise<PopulatedTransaction>;

    "initializeContract()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "registry()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "treasury()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    vaults(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "vaults(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
