/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICustodianInterface extends ethers.utils.Interface {
  functions: {
    "checkBorrowerEligibility(uint256,address)": FunctionFragment;
    "createVault(address,uint256)": FunctionFragment;
    "getVaultByOwner(address)": FunctionFragment;
    "requireSufficientCollateral(uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkBorrowerEligibility",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultByOwner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "requireSufficientCollateral",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkBorrowerEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireSufficientCollateral",
    data: BytesLike
  ): Result;

  events: {
    "VaultCreated(address,uint256)": EventFragment;
    "VaultDeleted(address,uint256)": EventFragment;
    "VaultUpdated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VaultUpdated"): EventFragment;
}

export class ICustodian extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICustodianInterface;

  functions: {
    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        index: BigNumber;
        collateral: BigNumber;
        equity: BigNumber;
        debt: BigNumber;
        status: number;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: number;
      };
    }>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        index: BigNumber;
        collateral: BigNumber;
        equity: BigNumber;
        debt: BigNumber;
        status: number;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: number;
      };
    }>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: void;
    }>;
  };

  checkBorrowerEligibility(
    debt: BigNumberish,
    borrower: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "checkBorrowerEligibility(uint256,address)"(
    debt: BigNumberish,
    borrower: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createVault(
    owner: string,
    initialCollateral: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createVault(address,uint256)"(
    owner: string,
    initialCollateral: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getVaultByOwner(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  "getVaultByOwner(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  requireSufficientCollateral(
    debt: BigNumberish,
    equity: BigNumberish,
    collateral: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  "requireSufficientCollateral(uint256,uint256,uint256)"(
    debt: BigNumberish,
    equity: BigNumberish,
    collateral: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    VaultCreated(owner: string | null, vaultId: null): EventFilter;

    VaultDeleted(owner: string | null, vaultId: null): EventFilter;

    VaultUpdated(owner: string | null, vaultId: null): EventFilter;
  };

  estimateGas: {
    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkBorrowerEligibility(
      debt: BigNumberish,
      borrower: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "checkBorrowerEligibility(uint256,address)"(
      debt: BigNumberish,
      borrower: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createVault(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createVault(address,uint256)"(
      owner: string,
      initialCollateral: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getVaultByOwner(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getVaultByOwner(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requireSufficientCollateral(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "requireSufficientCollateral(uint256,uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      collateral: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
