/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ILiquidation } from "./ILiquidation";

export class ILiquidationFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiquidation {
    return new Contract(address, _abi, signerOrProvider) as ILiquidation;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "vaultId",
        type: "uint256",
      },
    ],
    name: "Liquidation",
    type: "event",
  },
];
