/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import { Contract, ContractTransaction } from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ILiquidationInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "Liquidation(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Liquidation"): EventFragment;
}

export class ILiquidation extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ILiquidationInterface;

  functions: {};

  callStatic: {};

  filters: {
    Liquidation(owner: string | null, vaultId: null): EventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
