/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IProbityInterface extends ethers.utils.Interface {
  functions: {
    "addCollateral()": FunctionFragment;
    "closeVault()": FunctionFragment;
    "getVault()": FunctionFragment;
    "openVault(uint256,uint256)": FunctionFragment;
    "withdrawCollateral(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addCollateral",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openVault",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateral",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closeVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "openVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateral",
    data: BytesLike
  ): Result;

  events: {
    "VaultCreated(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "VaultCreated"): EventFragment;
}

export class IProbity extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IProbityInterface;

  functions: {
    addCollateral(overrides?: PayableOverrides): Promise<ContractTransaction>;

    "addCollateral()"(
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    closeVault(overrides?: Overrides): Promise<ContractTransaction>;

    "closeVault()"(overrides?: Overrides): Promise<ContractTransaction>;

    getVault(
      overrides?: CallOverrides
    ): Promise<{
      0: {
        index: BigNumber;
        collateral: BigNumber;
        equity: BigNumber;
        debt: BigNumber;
        status: number;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: number;
      };
    }>;

    "getVault()"(
      overrides?: CallOverrides
    ): Promise<{
      0: {
        index: BigNumber;
        collateral: BigNumber;
        equity: BigNumber;
        debt: BigNumber;
        status: number;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: number;
      };
    }>;

    openVault(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "openVault(uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    withdrawCollateral(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawCollateral(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  addCollateral(overrides?: PayableOverrides): Promise<ContractTransaction>;

  "addCollateral()"(overrides?: PayableOverrides): Promise<ContractTransaction>;

  closeVault(overrides?: Overrides): Promise<ContractTransaction>;

  "closeVault()"(overrides?: Overrides): Promise<ContractTransaction>;

  getVault(
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  "getVault()"(
    overrides?: CallOverrides
  ): Promise<{
    index: BigNumber;
    collateral: BigNumber;
    equity: BigNumber;
    debt: BigNumber;
    status: number;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: number;
  }>;

  openVault(
    debt: BigNumberish,
    equity: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "openVault(uint256,uint256)"(
    debt: BigNumberish,
    equity: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  withdrawCollateral(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawCollateral(uint256)"(
    _amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    addCollateral(overrides?: CallOverrides): Promise<void>;

    "addCollateral()"(overrides?: CallOverrides): Promise<void>;

    closeVault(overrides?: CallOverrides): Promise<void>;

    "closeVault()"(overrides?: CallOverrides): Promise<void>;

    getVault(
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    "getVault()"(
      overrides?: CallOverrides
    ): Promise<{
      index: BigNumber;
      collateral: BigNumber;
      equity: BigNumber;
      debt: BigNumber;
      status: number;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: number;
    }>;

    openVault(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "openVault(uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawCollateral(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawCollateral(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    VaultCreated(owner: string | null, vaultId: null): EventFilter;
  };

  estimateGas: {
    addCollateral(overrides?: PayableOverrides): Promise<BigNumber>;

    "addCollateral()"(overrides?: PayableOverrides): Promise<BigNumber>;

    closeVault(overrides?: Overrides): Promise<BigNumber>;

    "closeVault()"(overrides?: Overrides): Promise<BigNumber>;

    getVault(overrides?: CallOverrides): Promise<BigNumber>;

    "getVault()"(overrides?: CallOverrides): Promise<BigNumber>;

    openVault(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "openVault(uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    withdrawCollateral(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawCollateral(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCollateral(overrides?: PayableOverrides): Promise<PopulatedTransaction>;

    "addCollateral()"(
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    closeVault(overrides?: Overrides): Promise<PopulatedTransaction>;

    "closeVault()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getVault()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    openVault(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "openVault(uint256,uint256)"(
      debt: BigNumberish,
      equity: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    withdrawCollateral(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawCollateral(uint256)"(
      _amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
