/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IRegistryInterface extends ethers.utils.Interface {
  functions: {
    "getContractAddress(uint8)": FunctionFragment;
    "setupContractAddress(uint8,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getContractAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setupContractAddress",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setupContractAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IRegistryInterface;

  functions: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getContractAddress(
    name: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getContractAddress(uint8)"(
    name: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setupContractAddress(
    name: BigNumberish,
    _addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setupContractAddress(uint8,address)"(
    name: BigNumberish,
    _addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
