/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IRegistry } from "./IRegistry";

export class IRegistryFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRegistry {
    return new Contract(address, _abi, signerOrProvider) as IRegistry;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "enum ProbityBase.Contract",
        name: "name",
        type: "uint8",
      },
    ],
    name: "getContractAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "enum ProbityBase.Contract",
        name: "name",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "setupContractAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
