/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ITellerInterface extends ethers.utils.Interface {
  functions: {
    "createLoan(address,address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createLoan",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;

  events: {
    "LoanCreated(address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LoanCreated"): EventFragment;
}

export class ITeller extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ITellerInterface;

  functions: {
    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  createLoan(
    lender: string,
    borrower: string,
    principal: BigNumberish,
    rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createLoan(address,address,uint256,uint256)"(
    lender: string,
    borrower: string,
    principal: BigNumberish,
    rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    LoanCreated(
      lender: null,
      borrower: null,
      principal: null,
      rate: null,
      _now: null
    ): EventFilter;
  };

  estimateGas: {
    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
