/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ITreasuryInterface extends ethers.utils.Interface {
  functions: {
    "balanceOf(address)": FunctionFragment;
    "convertLenderEquityToLoan(address,address,uint256)": FunctionFragment;
    "decrease(uint256,address)": FunctionFragment;
    "increase(uint256,address)": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "withdrawEquity(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "convertLenderEquityToLoan",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decrease",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "increase",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEquity",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertLenderEquityToLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decrease", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "increase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEquity",
    data: BytesLike
  ): Result;

  events: {
    "TreasuryDecrease(address,uint256)": EventFragment;
    "TreasuryIncrease(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TreasuryDecrease"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasuryIncrease"): EventFragment;
}

export class ITreasury extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ITreasuryInterface;

  functions: {
    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertLenderEquityToLoan(
    lender: string,
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "convertLenderEquityToLoan(address,address,uint256)"(
    lender: string,
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  decrease(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "decrease(uint256,address)"(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  increase(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increase(uint256,address)"(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transfer(
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawEquity(
    owner: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawEquity(address,uint256)"(
    owner: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    TreasuryDecrease(owner: null, amount: null): EventFilter;

    TreasuryIncrease(owner: null, amount: null): EventFilter;
  };

  estimateGas: {
    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
