/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ProbityBaseInterface extends ethers.utils.Interface {
  functions: {
    "MIN_COLLATERAL_RATIO()": FunctionFragment;
    "ONE_HUNDRED_PERCENT()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MIN_COLLATERAL_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONE_HUNDRED_PERCENT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_COLLATERAL_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONE_HUNDRED_PERCENT",
    data: BytesLike
  ): Result;

  events: {};
}

export class ProbityBase extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ProbityBaseInterface;

  functions: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

  "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

  ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

  "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
