/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ProbityBase } from "./ProbityBase";

export class ProbityBaseFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ProbityBase> {
    return super.deploy(overrides || {}) as Promise<ProbityBase>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ProbityBase {
    return super.attach(address) as ProbityBase;
  }
  connect(signer: Signer): ProbityBaseFactory {
    return super.connect(signer) as ProbityBaseFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ProbityBase {
    return new Contract(address, _abi, signerOrProvider) as ProbityBase;
  }
}

const _abi = [
  {
    inputs: [],
    name: "MIN_COLLATERAL_RATIO",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ONE_HUNDRED_PERCENT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060e98061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80637a9fffb7146037578063dd0081c7146051575b600080fd5b603d606b565b604051604891906090565b60405180910390f35b60576077565b604051606291906090565b60405180910390f35b6714d1120d7b16000081565b670de0b6b3a764000081565b608a8160a9565b82525050565b600060208201905060a360008301846083565b92915050565b600081905091905056fea2646970667358221220d2b3ec4429c236fb729419fdc28fe99169ff6dd7edeeab69df404394ffa54d8964736f6c63430008000033";
