/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface RegistryInterface extends ethers.utils.Interface {
  functions: {
    "getContractAddress(uint8)": FunctionFragment;
    "isOwner()": FunctionFragment;
    "owner()": FunctionFragment;
    "setupContractAddress(uint8,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getContractAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setupContractAddress",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setupContractAddress",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Registry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: RegistryInterface;

  functions: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    isOwner(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isOwner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getContractAddress(
    name: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getContractAddress(uint8)"(
    name: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  setupContractAddress(
    name: BigNumberish,
    _addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setupContractAddress(uint8,address)"(
    name: BigNumberish,
    _addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getContractAddress(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getContractAddress(uint8)"(
      name: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setupContractAddress(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setupContractAddress(uint8,address)"(
      name: BigNumberish,
      _addr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
