/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TellerInterface extends ethers.utils.Interface {
  functions: {
    "MIN_COLLATERAL_RATIO()": FunctionFragment;
    "ONE_HUNDRED_PERCENT()": FunctionFragment;
    "balances(address)": FunctionFragment;
    "calculateInterest()": FunctionFragment;
    "createLoan(address,address,uint256,uint256)": FunctionFragment;
    "custodian()": FunctionFragment;
    "initializeContract()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "loanBalances(address,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "probity()": FunctionFragment;
    "registry()": FunctionFragment;
    "treasury()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MIN_COLLATERAL_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONE_HUNDRED_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "balances", values: [string]): string;
  encodeFunctionData(
    functionFragment: "calculateInterest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "custodian", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initializeContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "loanBalances",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "probity", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MIN_COLLATERAL_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONE_HUNDRED_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "custodian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "probity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;

  events: {
    "LoanCreated(address,address,uint256,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LoanCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class Teller extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TellerInterface;

  functions: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    calculateInterest(overrides?: Overrides): Promise<ContractTransaction>;

    "calculateInterest()"(overrides?: Overrides): Promise<ContractTransaction>;

    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    custodian(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "custodian()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    initializeContract(overrides?: Overrides): Promise<ContractTransaction>;

    "initializeContract()"(overrides?: Overrides): Promise<ContractTransaction>;

    isOwner(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isOwner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    loanBalances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interestRate: BigNumber;
      principal: BigNumber;
      duration: BigNumber;
      startDate: BigNumber;
      lender: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    "loanBalances(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interestRate: BigNumber;
      principal: BigNumber;
      duration: BigNumber;
      startDate: BigNumber;
      lender: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    probity(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "probity()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    registry(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "registry()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    treasury(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "treasury()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

  "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

  ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

  "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

  balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balances(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateInterest(overrides?: Overrides): Promise<ContractTransaction>;

  "calculateInterest()"(overrides?: Overrides): Promise<ContractTransaction>;

  createLoan(
    lender: string,
    borrower: string,
    principal: BigNumberish,
    rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createLoan(address,address,uint256,uint256)"(
    lender: string,
    borrower: string,
    principal: BigNumberish,
    rate: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  custodian(overrides?: CallOverrides): Promise<string>;

  "custodian()"(overrides?: CallOverrides): Promise<string>;

  initializeContract(overrides?: Overrides): Promise<ContractTransaction>;

  "initializeContract()"(overrides?: Overrides): Promise<ContractTransaction>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  loanBalances(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    interestRate: BigNumber;
    principal: BigNumber;
    duration: BigNumber;
    startDate: BigNumber;
    lender: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: string;
  }>;

  "loanBalances(address,uint256)"(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    interestRate: BigNumber;
    principal: BigNumber;
    duration: BigNumber;
    startDate: BigNumber;
    lender: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: string;
  }>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  probity(overrides?: CallOverrides): Promise<string>;

  "probity()"(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  "registry()"(overrides?: CallOverrides): Promise<string>;

  treasury(overrides?: CallOverrides): Promise<string>;

  "treasury()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateInterest(overrides?: CallOverrides): Promise<void>;

    "calculateInterest()"(overrides?: CallOverrides): Promise<void>;

    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    custodian(overrides?: CallOverrides): Promise<string>;

    "custodian()"(overrides?: CallOverrides): Promise<string>;

    initializeContract(overrides?: CallOverrides): Promise<void>;

    "initializeContract()"(overrides?: CallOverrides): Promise<void>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    loanBalances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interestRate: BigNumber;
      principal: BigNumber;
      duration: BigNumber;
      startDate: BigNumber;
      lender: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    "loanBalances(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      interestRate: BigNumber;
      principal: BigNumber;
      duration: BigNumber;
      startDate: BigNumber;
      lender: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
    }>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    probity(overrides?: CallOverrides): Promise<string>;

    "probity()"(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    "registry()"(overrides?: CallOverrides): Promise<string>;

    treasury(overrides?: CallOverrides): Promise<string>;

    "treasury()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    LoanCreated(
      lender: null,
      borrower: null,
      principal: null,
      rate: null,
      _now: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimateGas: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateInterest(overrides?: Overrides): Promise<BigNumber>;

    "calculateInterest()"(overrides?: Overrides): Promise<BigNumber>;

    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    custodian(overrides?: CallOverrides): Promise<BigNumber>;

    "custodian()"(overrides?: CallOverrides): Promise<BigNumber>;

    initializeContract(overrides?: Overrides): Promise<BigNumber>;

    "initializeContract()"(overrides?: Overrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    loanBalances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "loanBalances(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    probity(overrides?: CallOverrides): Promise<BigNumber>;

    "probity()"(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    "registry()"(overrides?: CallOverrides): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    "treasury()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateInterest(overrides?: Overrides): Promise<PopulatedTransaction>;

    "calculateInterest()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    createLoan(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createLoan(address,address,uint256,uint256)"(
      lender: string,
      borrower: string,
      principal: BigNumberish,
      rate: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    custodian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "custodian()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initializeContract(overrides?: Overrides): Promise<PopulatedTransaction>;

    "initializeContract()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    loanBalances(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "loanBalances(address,uint256)"(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    probity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "probity()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "registry()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "treasury()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
