/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TreasuryInterface extends ethers.utils.Interface {
  functions: {
    "MIN_COLLATERAL_RATIO()": FunctionFragment;
    "ONE_HUNDRED_PERCENT()": FunctionFragment;
    "aurei()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "balances(address)": FunctionFragment;
    "convertLenderEquityToLoan(address,address,uint256)": FunctionFragment;
    "custodian()": FunctionFragment;
    "decrease(uint256,address)": FunctionFragment;
    "increase(uint256,address)": FunctionFragment;
    "initializeContract()": FunctionFragment;
    "isOwner()": FunctionFragment;
    "owner()": FunctionFragment;
    "probity()": FunctionFragment;
    "registry()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "withdrawEquity(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MIN_COLLATERAL_RATIO",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONE_HUNDRED_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "aurei", values?: undefined): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(functionFragment: "balances", values: [string]): string;
  encodeFunctionData(
    functionFragment: "convertLenderEquityToLoan",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "custodian", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decrease",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "increase",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "probity", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEquity",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_COLLATERAL_RATIO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONE_HUNDRED_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aurei", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertLenderEquityToLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "custodian", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decrease", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "increase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "probity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEquity",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "TreasuryDecrease(address,uint256)": EventFragment;
    "TreasuryIncrease(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasuryDecrease"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TreasuryIncrease"): EventFragment;
}

export class Treasury extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TreasuryInterface;

  functions: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    aurei(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "aurei()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    custodian(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "custodian()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initializeContract(overrides?: Overrides): Promise<ContractTransaction>;

    "initializeContract()"(overrides?: Overrides): Promise<ContractTransaction>;

    isOwner(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isOwner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    owner(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "owner()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    probity(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "probity()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    registry(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "registry()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

  "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

  ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

  "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

  aurei(overrides?: CallOverrides): Promise<string>;

  "aurei()"(overrides?: CallOverrides): Promise<string>;

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balances(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  convertLenderEquityToLoan(
    lender: string,
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "convertLenderEquityToLoan(address,address,uint256)"(
    lender: string,
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  custodian(overrides?: CallOverrides): Promise<string>;

  "custodian()"(overrides?: CallOverrides): Promise<string>;

  decrease(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "decrease(uint256,address)"(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  increase(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increase(uint256,address)"(
    amount: BigNumberish,
    owner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initializeContract(overrides?: Overrides): Promise<ContractTransaction>;

  "initializeContract()"(overrides?: Overrides): Promise<ContractTransaction>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  probity(overrides?: CallOverrides): Promise<string>;

  "probity()"(overrides?: CallOverrides): Promise<string>;

  registry(overrides?: CallOverrides): Promise<string>;

  "registry()"(overrides?: CallOverrides): Promise<string>;

  transfer(
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transfer(address,uint256)"(
    borrower: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawEquity(
    owner: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawEquity(address,uint256)"(
    owner: string,
    amount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

    aurei(overrides?: CallOverrides): Promise<string>;

    "aurei()"(overrides?: CallOverrides): Promise<string>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    custodian(overrides?: CallOverrides): Promise<string>;

    "custodian()"(overrides?: CallOverrides): Promise<string>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initializeContract(overrides?: CallOverrides): Promise<void>;

    "initializeContract()"(overrides?: CallOverrides): Promise<void>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    "isOwner()"(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    probity(overrides?: CallOverrides): Promise<string>;

    "probity()"(overrides?: CallOverrides): Promise<string>;

    registry(overrides?: CallOverrides): Promise<string>;

    "registry()"(overrides?: CallOverrides): Promise<string>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    TreasuryDecrease(owner: null, amount: null): EventFilter;

    TreasuryIncrease(owner: null, amount: null): EventFilter;
  };

  estimateGas: {
    MIN_COLLATERAL_RATIO(overrides?: CallOverrides): Promise<BigNumber>;

    "MIN_COLLATERAL_RATIO()"(overrides?: CallOverrides): Promise<BigNumber>;

    ONE_HUNDRED_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "ONE_HUNDRED_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;

    aurei(overrides?: CallOverrides): Promise<BigNumber>;

    "aurei()"(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    custodian(overrides?: CallOverrides): Promise<BigNumber>;

    "custodian()"(overrides?: CallOverrides): Promise<BigNumber>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initializeContract(overrides?: Overrides): Promise<BigNumber>;

    "initializeContract()"(overrides?: Overrides): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "isOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    probity(overrides?: CallOverrides): Promise<BigNumber>;

    "probity()"(overrides?: CallOverrides): Promise<BigNumber>;

    registry(overrides?: CallOverrides): Promise<BigNumber>;

    "registry()"(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MIN_COLLATERAL_RATIO(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "MIN_COLLATERAL_RATIO()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ONE_HUNDRED_PERCENT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ONE_HUNDRED_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    aurei(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "aurei()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balances(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    convertLenderEquityToLoan(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "convertLenderEquityToLoan(address,address,uint256)"(
      lender: string,
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    custodian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "custodian()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decrease(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "decrease(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    increase(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increase(uint256,address)"(
      amount: BigNumberish,
      owner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initializeContract(overrides?: Overrides): Promise<PopulatedTransaction>;

    "initializeContract()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    probity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "probity()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "registry()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transfer(address,uint256)"(
      borrower: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawEquity(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawEquity(address,uint256)"(
      owner: string,
      amount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
